### ISSUE TITLE
Input argument rework (see TODO list inside)

### ISSUE THREAD

**Issue by erikhuizinga** [erikhuizinga/Bland-Altman-Analysis#13]
# Description

The input argument structure could be more optimised for ease of use. Some options, e.g. `'PlotStatistics'`, have many possibilities for their input arguments. This could be simplified by making it more explicit what possibility is being used. Instead of `'PlotStatistics'` with value `'none'`, `'basic'`, `'extended'` or `'regression'`, it would be better to use `'PlotStatistics', false`, `'PlotBasicStatistics', true`, etc. This does increase the number of Name-Value pair argument names, but this can be solved with the following helper function.

Because many options and Name-Value pair arguments can be specified, it would be useful to have a helper function that output an options structure (or object implementing checks for various dependent settings) that can be passed to `ba`. The helper function by default would generate a set of options useful for regular Bland-Altman analysis (BAA), but more advanced options can be seen there as well. This makes it easier for the user to find out what is possible by looking in the documentation for what the various options do.
# TODO
- [ ] Return structure `opts` with various fields (and subfields) containing values for the various options
- [ ] Create helper function that returns options for `ba`, e.g. `opts = baopts();` (or `baoptions()`, `bao()`, ...)
  - [ ] Return a default set of options useful for regular BAA
- [ ] Make existing Name-Value pair arguments more explicit by limiting their value options or by replacing all non-boolean Name-Value pair arguments with boolean ones
- [ ] Implement a Name-Value pair argument `Assume` (or `Assumptions`), which takes a `struct` value with fields for every assumption in BAA, e.g.:
  - [ ] Assume constant true value (default: `true` | `false`)
  - [ ] Assume constant bias (default: `true` | `false`)
  - [ ] Assume constant residual variance (default: `false` | `true`)
  - [ ] ... (edit this issue and add other assumptions)
