### ISSUE TITLE
Add README.md features (see TODO list inside)

### ISSUE THREAD

**Issue by erikhuizinga** [erikhuizinga/Bland-Altman-Analysis#7]
The README should contain
- [ ] installation instructions (link to wiki), see #6
- [ ] a download link to the [latest release](https://github.com/erikhuizinga/Bland-Altman-Analysis/releases/latest)
  - [ ] This should also be on the installation instructions page on the wiki, see #6.
- [ ] a reference to the documentation (wiki)
- [ ] demonstration of the function in action
  - [ ] a small demo data set with resulting statistics, e.g. bias and limits of agreement
  - [ ] the resulting graphs
